name: Publish Docker image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PAT }}

      - name: Docker build
        run: docker build --progress=plain  -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/automatic1111:latest -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/automatic1111:${{ github.ref_name }} .

      - name: Docker push
        run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/automatic1111  --all-tags
